# # 多语言支持
# 为了使用giscus,将languageCode改为了en zh-CN  https://github.com/CaiJimmy/hugo-theme-stack/issues/1096
# 原本是en-us zh-cn
en:
  languageName: "English"
  languageCode: "en"
  weight: 2
  contentDir: content/en
  languagedirection: "ltr"
  title: "AI News"
  params:
    description: "Share AI News."
    sidebar:
      subtitle: Share AI News daily
    keywords: "AI, daily hot,coze,dify,n8n,spacex,Agent"
zh-cn:
  languageName: "中文"
  languageCode: "zh-CN"
  weight: 1
  contentDir: content/zh-cn
  languagedirection: "ltr"
  title: "AI"
  params:
    description: "每天分享 AI 最热门的内容。发现大家都在谈论的最新AI移动应用、网站和技术产品。"
    sidebar:
      subtitle: 每天分享 AI 最热门的内容
    keywords: "AI,daily hot,coze,dify,n8n,spacex,人工智能,Agent"
