mainSections:
  - "post"
rssFullContent: true
favicon: "/favicon.png"

footer:
  since: 2020
  customText: ""

dateFormat:
  published: "Jan 02, 2006"
  lastUpdated: "Jan 02, 2006 15:04 MST"

sidebar:
  emoji: "🍥"
  subtitle: "Share Producthunt's hottest content daily"
  avatar:
    enabled: true
    local: true
    src: "img/avatar.png"

article:
  headingAnchor: false
  math: true
  readingTime: true
  license:
    enabled: true
    default: "Licensed under CC BY-NC-SA 4.0"

widgets:
  homepage:
    - type: "search"
    - type: "archives"
      params:
        limit: 5
    - type: "categories"
      params:
        limit: 10
    - type: "tag-cloud"
      params:
        limit: 10
  page:
    - type: "toc"

opengraph:
  twitter:
    site: ""
    card: "summary_large_image"

defaultImage:
  opengraph:
    enabled: false
    local: false
    src: ""

colorScheme:
  toggle: true
  default: "auto"

imageProcessing:
  cover:
    enabled: true
  content:
    enabled: true
# 配置文档 https://stack.jimmycai.com/config/comments
comments:
  enabled: true
  provider: "giscus"
  disqusjs:
    shortname: ""
    apiUrl: ""
    apiKey: ""
    admin: ""
    adminLabel: ""
  utterances:
    repo: ""
    issueTerm: "pathname"
    label: ""
  remark42:
    host: ""
    site: ""
    locale: ""
  vssue:
    platform: ""
    owner: ""
    repo: ""
    clientId: ""
    clientSecret: ""
    autoCreateIssue: false
  waline:
    serverURL: ""
    lang: ""
    visitor: ""
    avatar: ""
    emoji:
      - "https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"
    requiredMeta:
      - "name"
      - "email"
      - "url"
    placeholder: ""
    locale:
      admin: "Admin"
  twikoo:
    envId: ""
    region: ""
    path: ""
    lang: ""
  cactus:
    defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
    serverName: "cactus.chat"
    siteName: ""
  giscus:
    repo: "yiGmMk/comment_blog"
    repoID: "MDEwOlJlcG9zaXRvcnkxOTcyMTY4NDA="
    category: "Announcements"
    categoryID: "DIC_kwDOC8FKSM4CAcFc"
    mapping: "title"
    strict: "0" # Giscus的data-strict字段
    theme: "preferred_color_scheme"
    reactions: false
    reactionsEnabled: 1
    emitMetadata: 0
    loading: "lazy"
  gitalk:
    owner: ""
    admin: ""
    repo: ""
    clientID: ""
    clientSecret: ""
  cusdis:
    host: ""
    id: ""
