name: Generate Daily

on:
  schedule:
    - cron: "01 7 * * *" # 每天UTC时间早上7:01（北京时间下午3:01自动运行）
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install openai>=1.0.0
          pip install python-wordpress-xmlrpc

      # - name: Generate Markdown 中文
      #   env:
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #     OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
      #     PRODUCTHUNT_CLIENT_ID: ${{ secrets.PRODUCTHUNT_CLIENT_ID }}
      #     PRODUCTHUNT_CLIENT_SECRET: ${{ secrets.PRODUCTHUNT_CLIENT_SECRET }}
      #     LANGUAGE: "zh"
      #   run: |
      #     python scripts/multi_language.py

      # github flow 需要提交要在repo settings里添加secrets 并且,在Actions里开启Workflow permissions 的 "Read and write permissions"
      # 参考 https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
      - name: Commit and push if changed
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |-
          git diff
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git pull
          git add -A
          git commit -m "Generated daily content" || exit 0
          git push
